dist: trusty
language: elixir
elixir:
  - 1.8
  - 1.7
  - 1.6
otp_release:
  - 21.2
  - 21.1
  - 21.0
  - 20.3
  - 20.2
env:
  - CACHE_ENABLED=true  TEST_OPTS='--exclude phoenix_pubsub --exclude ecto_persistence'
  - CACHE_ENABLED=false TEST_OPTS='--only integration'
  - CACHE_ENABLED=true  PUBSUB_BROKER=phoenix_pubsub TEST_OPTS='--no-start --exclude redis_pubsub --exclude ecto_persistence --exclude phoenix_pubsub:with_ecto --include phoenix_pubsub:with_redis --include phoenix_pubsub:true' 
  - CACHE_ENABLED=false PUBSUB_BROKER=phoenix_pubsub TEST_OPTS='--no-start --only integration'
  - CACHE_ENABLED=true  PUBSUB_BROKER=phoenix_pubsub PERSISTENCE=ecto TEST_OPTS='--no-start --exclude redis_pubsub --exclude redis_persistence --exclude phoenix_pubsub:with_redis --include phoenix_pubsub:with_ecto --include phoenix_pubsub:true --include ecto_persistence' 
  - CACHE_ENABLED=false PUBSUB_BROKER=phoenix_pubsub PERSISTENCE=ecto TEST_OPTS='--no-start --only integration'
matrix:
  exclude:
    - elixir: 1.8
      otp_release: 21.0
    - elixir: 1.8
      otp_release: 20.3
    - elixir: 1.8
      otp_release: 20.2
    - elixir: 1.7
      otp_release: 20.3
    - elixir: 1.7
      otp_release: 20.2
    - elixir: 1.6
      otp_release: 21.2
    - elixir: 1.6
      otp_release: 21.1
    - elixir: 1.6
      otp_release: 21.0
services:
  - redis-server
addons:
  postgresql: "9.6"
script:
  - mix test --force $TEST_OPTS
before_script:
  - MIX_ENV=test mix ecto.create
  - MIX_ENV=test mix ecto.migrate
notifications:
  email:
    on_success: never
    on_failure: never
